name: Deploy

on: [push]

jobs:
  run_tests_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm install && CI=true npm test
      - name: Run backend tests
        working-directory: ./backend
        run: npm install && npm test
      - name: Run frontend lint
        working-directory: ./frontend
        run: npm run lint
