name: Deploy

on: [push]

jobs:
  build:
		runs-on: ubuntu-latest
		steps:
		  - uses: actions/checkout@v2
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm install && npm test
